export const demoRiskRows = [
  {
    id: "risk_s6_cm_10008",
    title: "10008 随机前抗组胺药洗脱不足",
    subject: "10008",
    site: "10",
    type: "禁用药/洗脱违规",
    severity: "high",
    status: "需行动",
    batch: "003",
    owner: "医学经理",
    source: "KRI-07 / 规则",
    age: "3h",
  },
  {
    id: "risk_s6_ae_06021",
    title: "06021 眼部异常与 AE 记录不一致",
    subject: "06021",
    site: "06",
    type: "AE/MH漏报",
    severity: "medium",
    status: "复核中",
    batch: "003",
    owner: "医学经理",
    source: "医学规则",
    age: "1d",
  },
  {
    id: "risk_s6_lab_10021",
    title: "10021 ALT 升高 Grade 2 未见医学解释",
    subject: "10021",
    site: "18",
    type: "实验室异常未解释",
    severity: "medium",
    status: "待确认",
    batch: "003",
    owner: "医学经理",
    source: "QTL-05 / 实验室",
    age: "1d",
  },
  {
    id: "risk_s6_eff_10045",
    title: "10045 rTNSS 连续两访视恶化且用药增加",
    subject: "10045",
    site: "03",
    type: "疗效偏离",
    severity: "medium",
    status: "复核中",
    batch: "003",
    owner: "医学经理",
    source: "趋势规则",
    age: "2d",
  },
  {
    id: "risk_s6_visit_10031",
    title: "10031 W4 访视窗口偏离 5 天",
    subject: "10031",
    site: "12",
    type: "访视偏离",
    severity: "low",
    status: "已关闭",
    batch: "002",
    owner: "CRA",
    source: "数据质量",
    age: "5d",
  },
];

export const demoSubjects = [
  {
    id: "10008",
    site: "10",
    status: "高风险复核",
    profile: "男 / 31岁 / 随机 D1 / ITT",
    efficacy: [
      { visit: "筛选", rTNSS: 8.6, iTNSS: 8.9, quality: 62 },
      { visit: "D1", rTNSS: 8.2, iTNSS: 8.5, quality: 64 },
      { visit: "W1", rTNSS: 6.9, iTNSS: 7.0, quality: 70 },
      { visit: "W2", rTNSS: 7.6, iTNSS: 7.4, quality: 66 },
      { visit: "W4", rTNSS: 7.8, iTNSS: 7.9, quality: 63 },
    ],
    timeline: [
      { day: "筛选-7", lane: "MH", label: "SAR 诊断史 5年", risk: "source" },
      { day: "筛选-3", lane: "CM", label: "氯雷他定开始", risk: "warning" },
      { day: "D1", lane: "访视", label: "随机", risk: "normal" },
      { day: "D2", lane: "CM", label: "氯雷他定结束", risk: "critical" },
      { day: "W1", lane: "疗效", label: "rTNSS 改善", risk: "good" },
      { day: "W2", lane: "疗效", label: "症状反弹", risk: "warning" },
      { day: "W4", lane: "PD", label: "潜在洗脱不足", risk: "critical" },
    ],
    risks: ["随机前4天内使用抗组胺药", "PD listing 未见对应记录", "W2 后疗效改善不稳定"],
    labs: [
      { name: "ALT", value: "28 U/L", trend: "稳定", flag: "normal" },
      { name: "EOS", value: "0.62 x10^9/L", trend: "升高", flag: "warning" },
      { name: "IgE", value: "198 IU/mL", trend: "基线高", flag: "info" },
    ],
    queries: ["CM 用药结束日期待中心确认", "是否构成方案偏离待医学确认"],
  },
  {
    id: "06021",
    site: "06",
    status: "中风险复核",
    profile: "女 / 42岁 / W4 / 安全集",
    efficacy: [
      { visit: "筛选", rTNSS: 7.9, iTNSS: 8.1, quality: 58 },
      { visit: "D1", rTNSS: 7.7, iTNSS: 8.0, quality: 59 },
      { visit: "W1", rTNSS: 6.3, iTNSS: 6.8, quality: 68 },
      { visit: "W2", rTNSS: 5.8, iTNSS: 6.1, quality: 72 },
      { visit: "W4", rTNSS: 5.5, iTNSS: 5.9, quality: 76 },
    ],
    timeline: [
      { day: "筛选", lane: "MH", label: "过敏性结膜炎史", risk: "source" },
      { day: "D1", lane: "访视", label: "随机", risk: "normal" },
      { day: "W1", lane: "AE", label: "眼痒记录于病历", risk: "warning" },
      { day: "W2", lane: "实验室", label: "EOS 下降", risk: "good" },
      { day: "W4", lane: "AE", label: "AE listing 未见眼部事件", risk: "warning" },
    ],
    risks: ["病历记录眼部症状但 AE listing 缺失", "同靶点 IB 眼部风险需医学复核"],
    labs: [
      { name: "ALT", value: "22 U/L", trend: "稳定", flag: "normal" },
      { name: "EOS", value: "0.31 x10^9/L", trend: "下降", flag: "normal" },
      { name: "结膜评分", value: "2", trend: "新增", flag: "warning" },
    ],
    queries: ["请中心确认眼部症状是否应作为 AE 记录"],
  },
];
