// Final-matrix scenario fixtures: 6 synthetic non-oncology indications
// covering Phase I/II/III with distinct designs per round.
// All facts are synthetic test data; no real clinical values.

export const SCENARIOS = {
  // Round 1
  asthma_p1: {
    id: "asthma_p1",
    round: 1,
    phase: "I期",
    indication: "哮喘",
    product: "SYN-AST-101",
    protocolId: "SYN-AST-101-101",
    projectCode: "QC-FINAL-AST-P1",
    projectName: "SYN-AST-101治疗哮喘的I期临床研究方案 最终矩阵验收",
    framing: {
      protocol_id: "SYN-AST-101",
      version: "V0.1",
      document_title: "SYN-AST-101治疗哮喘的I期临床研究方案",
      indication: "哮喘",
      clinicaltrials_condition_term: "Asthma",
      study_phase: "I期",
      intrinsic_objectives: ["安全性耐受性", "药代动力学"],
      investigational_product: "SYN-AST-101吸入剂",
      product_profile: {
        technology_type: "small_molecule",
        technology_description: "靶向气道炎症的小分子吸入剂",
        administration_routes: ["吸入"],
        dosage_forms: ["干粉吸入剂"],
        exposure_scope: "mixed",
        device_dependency: "integrated",
        immunogenicity_relevance: "not_expected",
        pharmacology_considerations: ["局部气道暴露与全身暴露的平衡"],
        safety_considerations: ["支气管痉挛风险", "QTc延长风险"],
        pk_pd_considerations: ["吸入后全身暴露的剂量比例性"],
      },
      structured_design: {
        schema_version: "medical_writing_structured_study_design_v2",
        randomization_mode: "randomized",
        randomization_details: "按队列内随机分配活性药与安慰剂",
        blinding_mode: "double_blind",
        blinded_roles: ["受试者", "研究者"],
        blinding_details: "活性药与安慰剂吸入装置外观一致",
        comparator_type: "placebo",
        comparator_intervention: "匹配安慰剂吸入剂",
        assignment_model: "哨兵给药后队列内平行分组",
        center_model: "单中心",
        treatment_switch: { planned: false },
        crossover: { planned: false },
        open_label_extension: { planned: false },
        sample_size_reestimation: { planned: false },
        adaptive_design: { planned: false },
        interim_analysis: { planned: false },
        src_planned: true,
        dmc_planned: false,
        arm_or_cohort_kind: "剂量队列",
        arm_or_cohort_labels: ["SYN-AST-101低剂量队列", "SYN-AST-101高剂量队列", "安慰剂队列"],
      },
      target_mechanism: "靶向气道炎症的小分子",
      competitor_target_scope: "同靶点吸入性抗炎药物",
      development_regions: ["中国"],
      design_pattern: "随机、双盲、安慰剂对照、哨兵给药、剂量递增、单中心SAD/MAD研究",
      population_intent: "健康成年志愿者",
      key_uncertainties: ["剂量比例性", "吸入装置依赖性全身暴露"],
    },
    picos: {
      design_archetype: "single_arm_early_phase",
      population_summary: "18至55岁健康成年志愿者。",
      inclusion_modules: ["健康志愿者标准筛选", "肺功能基线正常"],
      exclusion_modules: ["近期呼吸道感染", "已知吸入剂过敏"],
      washout_rules: ["筛选前两周内未使用任何处方药"],
      intervention_summary: "SYN-AST-101两个剂量水平，经口吸入。",
      intervention_dose_regimen: "SAD阶段单次给药；MAD阶段每日一次连续7天。",
      intervention_rules: {
        schema_version: "medical_writing_intervention_rules_v1",
        authority: "structured",
        ip_regimens: [
          {
            regimen_id: "syn-ast-101-sad-low",
            product_name: "SYN-AST-101低剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验低剂量，单次吸入",
            route: "经口吸入",
            treatment_period: "SAD单次给药",
          },
          {
            regimen_id: "syn-ast-101-mad-high",
            product_name: "SYN-AST-101高剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验高剂量，每日一次",
            route: "经口吸入",
            treatment_period: "MAD连续7天",
          },
          {
            regimen_id: "matched-placebo-inhaler",
            product_name: "匹配安慰剂吸入剂",
            product_role: "placebo",
            dose_and_frequency: "与活性药相同频率",
            route: "经口吸入",
            treatment_period: "SAD/MAD各阶段",
          },
        ],
        ip_adjustment_policy: "protocol_defined",
        no_planned_adjustment_statement: "",
        ip_action_rules: [
          {
            rule_id: "src-sentinel-escalation",
            action_kind: "other",
            trigger: "哨兵受试者完成给药并完成安全性观察窗",
            study_product_action: "由SRC评估安全性后决定是否进入下一剂量队列",
            linked_non_ip_rule_ids: [],
          },
        ],
        non_ip_treatment_rules: [
          {
            rule_id: "prohibited-bronchodilator",
            rule_class: "prohibited_cm",
            policy: "prohibited",
            agent_or_category: "短效和长效支气管扩张剂",
            phase_applicability: "筛选期至随访期",
          },
        ],
      },
      allowed_concomitant_rules: ["对乙酰氨基酚用于头痛"],
      required_background_rules: [],
      prohibited_concomitant_rules: ["支气管扩张剂", "吸入性糖皮质激素"],
      assessment_timing_restrictions: ["PK采样前禁食"],
      comparator_summary: "匹配安慰剂吸入剂。",
      primary_endpoint: "TEAE和SAE发生率。",
      key_secondary_endpoints: ["血浆PK参数Cmax和AUC"],
      other_secondary_endpoints: ["尿药代参数"],
      exploratory_endpoints: ["呼出气一氧化氮变化"],
      safety_endpoints: ["生命体征、心电图、实验室检查"],
      aesi_definitions: ["支气管痉挛", "QTc延长"],
      study_epochs: ["筛选期", "SAD给药期", "MAD给药期", "随访期"],
      visit_strategy: "筛选、入院给药、PK密集采样、出院随访。",
      estimand_strategy: "安全性估计目标评价各剂量水平耐受性。",
      sample_size_strategy: "基于安全性队列规模，非统计效力驱动。",
      statistical_strategy: "描述性安全性分析；PK参数非房室分析。",
    },
    // UI assertion tokens
    synopsisToken: "SYN-AST-101治疗哮喘的I期临床研究方案",
    designTokens: ["随机化", "双盲", "安慰剂"],
    aiInstruction: "请仅对本次选中文字做专业医学中文润色，保持哨兵给药、剂量递增、双盲、安慰剂对照、研究阶段、时间点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。",
  },

  ra_p2: {
    id: "ra_p2",
    round: 1,
    phase: "II期",
    indication: "类风湿关节炎",
    product: "SYN-RA-201",
    protocolId: "SYN-RA-201-201",
    projectCode: "QC-FINAL-RA-P2",
    projectName: "SYN-RA-201治疗类风湿关节炎的II期临床研究方案 最终矩阵验收",
    framing: {
      protocol_id: "SYN-RA-201",
      version: "V0.1",
      document_title: "SYN-RA-201治疗类风湿关节炎的II期临床研究方案",
      indication: "类风湿关节炎",
      clinicaltrials_condition_term: "Rheumatoid Arthritis",
      study_phase: "II期",
      intrinsic_objectives: ["概念验证（PoC）", "剂量探索"],
      investigational_product: "SYN-RA-201注射液",
      product_profile: {
        technology_type: "monoclonal_antibody",
        technology_description: "靶向炎症通路的单克隆抗体",
        administration_routes: ["皮下注射"],
        dosage_forms: ["注射液"],
        exposure_scope: "systemic",
        device_dependency: "none",
        immunogenicity_relevance: "potential",
        pharmacology_considerations: ["靶向炎症通路"],
        safety_considerations: ["严重感染风险", "超敏反应风险"],
        pk_pd_considerations: ["给药间隔内暴露与疗效的关系"],
      },
      structured_design: {
        schema_version: "medical_writing_structured_study_design_v2",
        randomization_mode: "randomized",
        randomization_details: "按中心和基线疾病活动度分层随机",
        blinding_mode: "double_blind",
        blinded_roles: ["受试者", "研究者", "疗效评价者"],
        blinding_details: "试验药与安慰剂外观和给药方式匹配",
        comparator_type: "placebo",
        comparator_intervention: "匹配安慰剂",
        assignment_model: "平行分组，1:1:1分配",
        center_model: "多中心",
        treatment_switch: { planned: false },
        crossover: { planned: false },
        open_label_extension: { planned: false },
        sample_size_reestimation: { planned: false },
        adaptive_design: { planned: false },
        interim_analysis: { planned: false },
        src_planned: false,
        dmc_planned: false,
        arm_or_cohort_kind: "治疗组",
        arm_or_cohort_labels: ["SYN-RA-201低剂量组", "SYN-RA-201高剂量组", "安慰剂组"],
      },
      target_mechanism: "靶向炎症通路的单克隆抗体",
      competitor_target_scope: "同靶点及同机制生物制剂",
      development_regions: ["中国"],
      design_pattern: "随机、双盲、安慰剂对照、平行组、多中心剂量探索研究",
      population_intent: "既往csDMARD治疗反应不充分的中重度活动性类风湿关节炎成人患者",
      key_uncertainties: ["剂量-效应关系", "第12周主要终点评价时点"],
    },
    picos: {
      design_archetype: "randomized_confirmatory",
      population_summary: "18至75岁中重度活动性类风湿关节炎试验参与者。",
      inclusion_modules: ["筛选期与基线期满足疾病活动度阈值", "稳定使用背景甲氨蝶呤"],
      exclusion_modules: ["活动性感染", "近期使用其他生物制剂且未完成洗脱"],
      washout_rules: ["既往生物制剂按药代特征和方案规定完成洗脱"],
      intervention_summary: "SYN-RA-201两个剂量组，皮下注射。",
      intervention_dose_regimen: "每4周给药一次，持续24周。",
      intervention_rules: {
        schema_version: "medical_writing_intervention_rules_v1",
        authority: "structured",
        ip_regimens: [
          {
            regimen_id: "syn-ra-201-low",
            product_name: "SYN-RA-201低剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验低剂量，每4周一次",
            route: "皮下注射",
            treatment_period: "双盲治疗期24周",
          },
          {
            regimen_id: "syn-ra-201-high",
            product_name: "SYN-RA-201高剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验高剂量，每4周一次",
            route: "皮下注射",
            treatment_period: "双盲治疗期24周",
          },
          {
            regimen_id: "matched-placebo",
            product_name: "匹配安慰剂",
            product_role: "placebo",
            dose_and_frequency: "每4周一次",
            route: "皮下注射",
            treatment_period: "双盲治疗期24周",
          },
        ],
        ip_adjustment_policy: "no_planned_adjustment",
        no_planned_adjustment_statement: "无计划剂量调整；如发生预设安全性事件，按方案停药规则处理。",
        non_ip_treatment_rules: [
          {
            rule_id: "background-methotrexate",
            rule_class: "background",
            policy: "allowed_if_stable",
            agent_or_category: "稳定剂量甲氨蝶呤",
            phase_applicability: "筛选期至治疗期",
          },
          {
            rule_id: "prohibited-biologic",
            rule_class: "prohibited_cm",
            policy: "prohibited",
            agent_or_category: "其他生物制剂和JAK抑制剂",
            phase_applicability: "筛选期至治疗期",
          },
        ],
      },
      allowed_concomitant_rules: ["稳定剂量叶酸"],
      required_background_rules: ["稳定剂量甲氨蝶呤"],
      prohibited_concomitant_rules: ["其他生物制剂", "JAK抑制剂"],
      assessment_timing_restrictions: ["疗效评估前限制使用救援性糖皮质激素"],
      comparator_summary: "匹配安慰剂，每4周皮下注射一次。",
      primary_endpoint: "第12周ACR20应答率。",
      key_secondary_endpoints: ["第12周DAS28-CRP较基线变化"],
      other_secondary_endpoints: ["第24周ACR50和ACR70应答率"],
      exploratory_endpoints: ["炎症生物标志物较基线变化"],
      safety_endpoints: ["TEAE、SAE及导致停药的AE发生率"],
      aesi_definitions: ["严重感染", "超敏反应"],
      study_epochs: ["筛选期", "双盲治疗期", "安全性随访期"],
      visit_strategy: "筛选、基线，治疗期每4周访视，末次给药后完成安全性随访。",
      estimand_strategy: "主要估计目标评价治疗策略下第12周ACR20应答差异。",
      sample_size_strategy: "基于预期应答率差异、双侧显著性水平和脱落率估算。",
      statistical_strategy: "主要终点采用分层分析并进行多重性控制。",
    },
    synopsisToken: "SYN-RA-201治疗类风湿关节炎的II期临床研究方案",
    designTokens: ["随机化", "双盲", "安慰剂对照"],
    aiInstruction: "请仅对本次选中文字做专业医学中文润色，保持随机化、双盲、安慰剂对照、研究阶段、时间点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。",
  },

  hypertension_p3: {
    id: "hypertension_p3",
    round: 1,
    phase: "III期",
    indication: "高血压",
    product: "SYN-HTN-301",
    protocolId: "SYN-HTN-301-301",
    projectCode: "QC-FINAL-HTN-P3",
    projectName: "SYN-HTN-301治疗高血压的III期临床研究方案 最终矩阵验收",
    framing: {
      protocol_id: "SYN-HTN-301",
      version: "V0.1",
      document_title: "SYN-HTN-301治疗高血压的III期临床研究方案",
      indication: "高血压",
      clinicaltrials_condition_term: "Hypertension",
      study_phase: "III期",
      intrinsic_objectives: ["确证性疗效", "安全性"],
      investigational_product: "SYN-HTN-301片",
      product_profile: {
        technology_type: "small_molecule",
        technology_description: "新型血管紧张素受体拮抗剂",
        administration_routes: ["口服"],
        dosage_forms: ["片剂"],
        exposure_scope: "systemic",
        device_dependency: "none",
        immunogenicity_relevance: "not_expected",
        pharmacology_considerations: ["RAAS系统抑制"],
        safety_considerations: ["低血压风险", "高钾血症风险", "肾功能影响"],
        pk_pd_considerations: ["谷峰比与24小时血压控制"],
      },
      structured_design: {
        schema_version: "medical_writing_structured_study_design_v2",
        randomization_mode: "randomized",
        randomization_details: "按中心分层区组随机",
        blinding_mode: "double_blind",
        blinded_roles: ["受试者", "研究者", "终点评价者"],
        blinding_details: "试验药与活性对照药外观匹配（双模拟）",
        comparator_type: "active",
        comparator_intervention: "已上市ARB类药物",
        assignment_model: "平行分组，1:1分配",
        center_model: "多中心",
        treatment_switch: { planned: false },
        crossover: { planned: false },
        open_label_extension: { planned: false },
        sample_size_reestimation: { planned: false },
        adaptive_design: { planned: false },
        interim_analysis: { planned: false },
        src_planned: false,
        dmc_planned: true,
        arm_or_cohort_kind: "治疗组",
        arm_or_cohort_labels: ["SYN-HTN-301组", "活性对照组"],
      },
      target_mechanism: "血管紧张素II受体拮抗",
      competitor_target_scope: "同靶点ARB类药物",
      development_regions: ["中国"],
      design_pattern: "随机、双盲、活性对照、非劣效、平行组、多中心确证性研究",
      population_intent: "原发性高血压成人患者",
      key_uncertainties: ["非劣效界值选择", "长期心血管安全性"],
    },
    picos: {
      design_archetype: "randomized_confirmatory",
      population_summary: "18至80岁原发性高血压试验参与者。",
      inclusion_modules: ["坐位收缩压和舒张压满足入组阈值", "稳定生活方式"],
      exclusion_modules: ["继发性高血压", "近期心血管事件"],
      washout_rules: ["既往降压药按半衰期完成洗脱"],
      intervention_summary: "SYN-HTN-301每日一次口服。",
      intervention_dose_regimen: "每日一次，持续12周。",
      intervention_rules: {
        schema_version: "medical_writing_intervention_rules_v1",
        authority: "structured",
        ip_regimens: [
          {
            regimen_id: "syn-htn-301",
            product_name: "SYN-HTN-301",
            product_role: "investigational_product",
            dose_and_frequency: "试验剂量，每日一次",
            route: "口服",
            treatment_period: "双盲治疗期12周",
          },
          {
            regimen_id: "active-comparator-arb",
            product_name: "已上市ARB活性对照",
            product_role: "active_comparator",
            dose_and_frequency: "标准剂量，每日一次",
            route: "口服",
            treatment_period: "双盲治疗期12周",
          },
        ],
        ip_adjustment_policy: "no_planned_adjustment",
        no_planned_adjustment_statement: "无计划剂量调整；血压未控制者按方案退出标准处理。",
        non_ip_treatment_rules: [
          {
            rule_id: "prohibited-other-antihypertensive",
            rule_class: "prohibited_cm",
            policy: "prohibited",
            agent_or_category: "其他降压药物",
            phase_applicability: "筛选期至治疗期",
          },
        ],
      },
      allowed_concomitant_rules: ["稳定剂量他汀"],
      required_background_rules: [],
      prohibited_concomitant_rules: ["其他降压药", "NSAIDs长期使用"],
      assessment_timing_restrictions: ["ABPM佩戴前避免咖啡因"],
      comparator_summary: "已上市ARB类药物，每日一次口服。",
      primary_endpoint: "第12周坐位舒张压较基线变化（非劣效）。",
      key_secondary_endpoints: ["第12周坐位收缩压较基线变化"],
      other_secondary_endpoints: ["血压达标率"],
      exploratory_endpoints: ["24小时动态血压参数"],
      safety_endpoints: ["TEAE、SAE、实验室检查异常"],
      aesi_definitions: ["症状性低血压", "高钾血症", "肾功能恶化"],
      study_epochs: ["筛选期", "洗脱期", "双盲治疗期", "随访期"],
      visit_strategy: "筛选、洗脱、基线，治疗期每4周访视，末次给药后随访。",
      estimand_strategy: "主要估计目标评价治疗策略下第12周舒张压变化的非劣效性。",
      sample_size_strategy: "基于非劣效界值、单侧显著性水平和把握度估算。",
      statistical_strategy: "主要终点采用ANCOVA调整基线；非劣效基于置信区间下界。",
    },
    synopsisToken: "SYN-HTN-301治疗高血压的III期临床研究方案",
    designTokens: ["随机", "双盲", "阳性药对照"],
    aiInstruction: "请仅对本次选中文字做专业医学中文润色，保持随机化、双盲、活性对照、非劣效、研究阶段、时间点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。",
  },

  // Round 2
  migraine_p1: {
    id: "migraine_p1",
    round: 2,
    phase: "I期",
    indication: "偏头痛",
    product: "SYN-MIG-102",
    protocolId: "SYN-MIG-102-102",
    projectCode: "QC-FINAL-MIG-P1",
    projectName: "SYN-MIG-102治疗偏头痛的I期临床研究方案 最终矩阵验收",
    framing: {
      protocol_id: "SYN-MIG-102",
      version: "V0.1",
      document_title: "SYN-MIG-102治疗偏头痛的I期临床研究方案",
      indication: "偏头痛",
      clinicaltrials_condition_term: "Migraine",
      study_phase: "I期",
      intrinsic_objectives: ["安全性耐受性", "药代动力学"],
      investigational_product: "SYN-MIG-102鼻喷剂",
      product_profile: {
        technology_type: "small_molecule",
        technology_description: "CGRP受体拮抗剂鼻喷剂",
        administration_routes: ["鼻腔给药"],
        dosage_forms: ["鼻喷剂"],
        exposure_scope: "systemic",
        device_dependency: "integrated",
        immunogenicity_relevance: "not_expected",
        pharmacology_considerations: ["鼻腔黏膜吸收速率"],
        safety_considerations: ["鼻腔刺激", "血压升高"],
        pk_pd_considerations: ["鼻喷给药后快速达峰"],
      },
      structured_design: {
        schema_version: "medical_writing_structured_study_design_v2",
        randomization_mode: "randomized",
        randomization_details: "队列内顺序哨兵后随机",
        blinding_mode: "double_blind",
        blinded_roles: ["受试者", "研究者"],
        blinding_details: "活性药与安慰剂鼻喷装置外观一致",
        comparator_type: "placebo",
        comparator_intervention: "匹配安慰剂鼻喷剂",
        assignment_model: "顺序哨兵后队列内平行分组",
        center_model: "单中心",
        treatment_switch: { planned: false },
        crossover: { planned: false },
        open_label_extension: { planned: false },
        sample_size_reestimation: { planned: false },
        adaptive_design: { planned: false },
        interim_analysis: { planned: false },
        src_planned: true,
        dmc_planned: false,
        arm_or_cohort_kind: "剂量队列",
        arm_or_cohort_labels: ["SYN-MIG-102低剂量队列", "SYN-MIG-102高剂量队列", "安慰剂队列"],
      },
      target_mechanism: "CGRP受体拮抗",
      competitor_target_scope: "同靶点CGRP通路药物",
      development_regions: ["中国"],
      design_pattern: "随机、双盲、安慰剂对照、顺序哨兵、剂量递增、单中心研究",
      population_intent: "健康成年志愿者",
      key_uncertainties: ["鼻腔生物利用度", "剂量递增耐受性"],
    },
    picos: {
      design_archetype: "single_arm_early_phase",
      population_summary: "18至50岁健康成年志愿者。",
      inclusion_modules: ["健康志愿者标准筛选", "鼻腔检查正常"],
      exclusion_modules: ["慢性鼻炎", "近期鼻腔手术"],
      washout_rules: ["筛选前两周内未使用任何处方药"],
      intervention_summary: "SYN-MIG-102两个剂量水平，鼻腔给药。",
      intervention_dose_regimen: "SAD单次给药；MAD每日一次连续5天。",
      intervention_rules: {
        schema_version: "medical_writing_intervention_rules_v1",
        authority: "structured",
        ip_regimens: [
          {
            regimen_id: "syn-mig-102-sad-low",
            product_name: "SYN-MIG-102低剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验低剂量，单次鼻喷",
            route: "鼻腔给药",
            treatment_period: "SAD单次给药",
          },
          {
            regimen_id: "syn-mig-102-mad-high",
            product_name: "SYN-MIG-102高剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验高剂量，每日一次",
            route: "鼻腔给药",
            treatment_period: "MAD连续5天",
          },
          {
            regimen_id: "matched-placebo-nasal",
            product_name: "匹配安慰剂鼻喷剂",
            product_role: "placebo",
            dose_and_frequency: "与活性药相同频率",
            route: "鼻腔给药",
            treatment_period: "SAD/MAD各阶段",
          },
        ],
        ip_adjustment_policy: "protocol_defined",
        no_planned_adjustment_statement: "",
        ip_action_rules: [
          {
            rule_id: "src-sequential-sentinel-escalation",
            action_kind: "other",
            trigger: "顺序哨兵受试者完成给药并完成安全性观察窗",
            study_product_action: "由SRC评估安全性后决定是否进入下一剂量队列",
            linked_non_ip_rule_ids: [],
          },
        ],
        non_ip_treatment_rules: [
          {
            rule_id: "prohibited-triptan",
            rule_class: "prohibited_cm",
            policy: "prohibited",
            agent_or_category: "曲普坦类药物",
            phase_applicability: "筛选期至随访期",
          },
        ],
      },
      allowed_concomitant_rules: ["对乙酰氨基酚用于头痛"],
      required_background_rules: [],
      prohibited_concomitant_rules: ["曲普坦类", "CGRP靶向药物"],
      assessment_timing_restrictions: ["PK采样前禁食"],
      comparator_summary: "匹配安慰剂鼻喷剂。",
      primary_endpoint: "TEAE和SAE发生率。",
      key_secondary_endpoints: ["血浆PK参数Cmax和AUC"],
      other_secondary_endpoints: ["鼻腔局部耐受性评分"],
      exploratory_endpoints: ["CGRP水平变化"],
      safety_endpoints: ["生命体征、心电图、实验室检查"],
      aesi_definitions: ["鼻腔严重刺激", "血压显著升高"],
      study_epochs: ["筛选期", "SAD给药期", "MAD给药期", "随访期"],
      visit_strategy: "筛选、入院给药、PK密集采样、出院随访。",
      estimand_strategy: "安全性估计目标评价各剂量水平耐受性。",
      sample_size_strategy: "基于安全性队列规模，非统计效力驱动。",
      statistical_strategy: "描述性安全性分析；PK参数非房室分析。",
    },
    synopsisToken: "SYN-MIG-102治疗偏头痛的I期临床研究方案",
    designTokens: ["随机化", "双盲", "安慰剂"],
    aiInstruction: "请仅对本次选中文字做专业医学中文润色，保持顺序哨兵、剂量递增、双盲、安慰剂对照、研究阶段、时间点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。",
  },

  t2d_p2: {
    id: "t2d_p2",
    round: 2,
    phase: "II期",
    indication: "2型糖尿病",
    product: "SYN-T2D-202",
    protocolId: "SYN-T2D-202-202",
    projectCode: "QC-FINAL-T2D-P2",
    projectName: "SYN-T2D-202治疗2型糖尿病的II期临床研究方案 最终矩阵验收",
    framing: {
      protocol_id: "SYN-T2D-202",
      version: "V0.1",
      document_title: "SYN-T2D-202治疗2型糖尿病的II期临床研究方案",
      indication: "2型糖尿病",
      clinicaltrials_condition_term: "Type 2 Diabetes Mellitus",
      study_phase: "II期",
      intrinsic_objectives: ["概念验证（PoC）", "剂量探索"],
      investigational_product: "SYN-T2D-202片",
      product_profile: {
        technology_type: "small_molecule",
        technology_description: "新型GLP-1/GIP双靶点激动剂口服制剂",
        administration_routes: ["口服"],
        dosage_forms: ["片剂"],
        exposure_scope: "systemic",
        device_dependency: "none",
        immunogenicity_relevance: "not_expected",
        pharmacology_considerations: ["肠促胰素双靶点协同"],
        safety_considerations: ["胃肠道不良反应", "低血糖风险"],
        pk_pd_considerations: ["口服生物利用度与进食效应"],
      },
      structured_design: {
        schema_version: "medical_writing_structured_study_design_v2",
        randomization_mode: "randomized",
        randomization_details: "按中心和基线HbA1c分层区组随机",
        blinding_mode: "double_blind",
        blinded_roles: ["受试者", "研究者", "终点评价者"],
        blinding_details: "各剂量组与安慰剂片剂外观匹配",
        comparator_type: "placebo",
        comparator_intervention: "匹配安慰剂片",
        assignment_model: "2x2析因设计，剂量与背景治疗两个因素",
        center_model: "多中心",
        treatment_switch: { planned: false },
        crossover: { planned: false },
        open_label_extension: { planned: false },
        sample_size_reestimation: { planned: false },
        adaptive_design: { planned: false },
        interim_analysis: { planned: false },
        src_planned: false,
        dmc_planned: false,
        arm_or_cohort_kind: "治疗组",
        arm_or_cohort_labels: ["SYN-T2D-202低剂量+二甲双胍", "SYN-T2D-202高剂量+二甲双胍", "SYN-T2D-202低剂量+安慰剂背景", "SYN-T2D-202高剂量+安慰剂背景", "全安慰剂组"],
      },
      target_mechanism: "GLP-1/GIP双靶点激动",
      competitor_target_scope: "同靶点肠促胰素类药物",
      development_regions: ["中国"],
      design_pattern: "随机、双盲、安慰剂对照、析因设计、剂量探索、多中心研究",
      population_intent: "二甲双胍单药控制不佳的2型糖尿病成人患者",
      key_uncertainties: ["剂量-效应关系", "析因交互作用"],
    },
    picos: {
      design_archetype: "randomized_confirmatory",
      population_summary: "18至70岁2型糖尿病试验参与者。",
      inclusion_modules: ["HbA1c满足入组阈值", "稳定使用二甲双胍"],
      exclusion_modules: ["1型糖尿病", "近期严重低血糖事件"],
      washout_rules: ["既往GLP-1类药物按半衰期完成洗脱"],
      intervention_summary: "SYN-T2D-202两个剂量水平，口服，析因设计。",
      intervention_dose_regimen: "每日一次，持续16周。",
      intervention_rules: {
        schema_version: "medical_writing_intervention_rules_v1",
        authority: "structured",
        ip_regimens: [
          {
            regimen_id: "syn-t2d-202-low",
            product_name: "SYN-T2D-202低剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验低剂量，每日一次",
            route: "口服",
            treatment_period: "双盲治疗期16周",
          },
          {
            regimen_id: "syn-t2d-202-high",
            product_name: "SYN-T2D-202高剂量",
            product_role: "investigational_product",
            dose_and_frequency: "试验高剂量，每日一次",
            route: "口服",
            treatment_period: "双盲治疗期16周",
          },
          {
            regimen_id: "matched-placebo-tablet",
            product_name: "匹配安慰剂片",
            product_role: "placebo",
            dose_and_frequency: "每日一次",
            route: "口服",
            treatment_period: "双盲治疗期16周",
          },
        ],
        ip_adjustment_policy: "no_planned_adjustment",
        no_planned_adjustment_statement: "无计划剂量调整；如发生预设安全性事件，按方案停药规则处理。",
        non_ip_treatment_rules: [
          {
            rule_id: "background-metformin",
            rule_class: "background",
            policy: "allowed_if_stable",
            agent_or_category: "稳定剂量二甲双胍",
            phase_applicability: "筛选期至治疗期",
          },
          {
            rule_id: "prohibited-insulin",
            rule_class: "prohibited_cm",
            policy: "prohibited",
            agent_or_category: "胰岛素和其他GLP-1类药物",
            phase_applicability: "筛选期至治疗期",
          },
        ],
      },
      allowed_concomitant_rules: ["稳定剂量二甲双胍"],
      required_background_rules: ["稳定剂量二甲双胍"],
      prohibited_concomitant_rules: ["胰岛素", "其他GLP-1类药物", "SGLT2抑制剂"],
      assessment_timing_restrictions: ["OGTT前禁食"],
      comparator_summary: "匹配安慰剂片，每日一次口服。",
      primary_endpoint: "第16周HbA1c较基线变化。",
      key_secondary_endpoints: ["第16周空腹血糖较基线变化"],
      other_secondary_endpoints: ["体重较基线变化"],
      exploratory_endpoints: ["胰岛素抵抗指数变化"],
      safety_endpoints: ["TEAE、SAE、低血糖事件"],
      aesi_definitions: ["严重低血糖", "胰腺炎"],
      study_epochs: ["筛选期", "导入期", "双盲治疗期", "随访期"],
      visit_strategy: "筛选、导入、基线，治疗期每4周访视，末次给药后随访。",
      estimand_strategy: "主要估计目标评价治疗策略下第16周HbA1c变化；析因估计评价交互作用。",
      sample_size_strategy: "基于析因设计主效应和交互作用检验的把握度估算。",
      statistical_strategy: "析因方差分析评价主效应和交互作用；多重性控制。",
    },
    synopsisToken: "SYN-T2D-202治疗2型糖尿病的II期临床研究方案",
    designTokens: ["随机化", "双盲", "安慰剂"],
    aiInstruction: "请仅对本次选中文字做专业医学中文润色，保持析因设计、随机化、双盲、安慰剂对照、研究阶段、时间点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。",
  },

  copd_p3: {
    id: "copd_p3",
    round: 2,
    phase: "III期",
    indication: "慢性阻塞性肺疾病",
    product: "SYN-COPD-302",
    protocolId: "SYN-COPD-302-302",
    projectCode: "QC-FINAL-COPD-P3",
    projectName: "SYN-COPD-302治疗慢性阻塞性肺疾病的III期临床研究方案 最终矩阵验收",
    framing: {
      protocol_id: "SYN-COPD-302",
      version: "V0.1",
      document_title: "SYN-COPD-302治疗慢性阻塞性肺疾病的III期临床研究方案",
      indication: "慢性阻塞性肺疾病",
      clinicaltrials_condition_term: "Chronic Obstructive Pulmonary Disease",
      study_phase: "III期",
      intrinsic_objectives: ["确证性疗效", "安全性"],
      investigational_product: "SYN-COPD-302吸入粉雾剂",
      product_profile: {
        technology_type: "small_molecule",
        technology_description: "长效 muscarinic 受体拮抗剂吸入制剂",
        administration_routes: ["吸入"],
        dosage_forms: ["干粉吸入剂"],
        exposure_scope: "mixed",
        device_dependency: "integrated",
        immunogenicity_relevance: "not_expected",
        pharmacology_considerations: ["长效支气管扩张"],
        safety_considerations: ["心血管事件", "尿潴留"],
        pk_pd_considerations: ["吸入后全身暴露低"],
      },
      structured_design: {
        schema_version: "medical_writing_structured_study_design_v2",
        randomization_mode: "randomized",
        randomization_details: "按中心和基线FEV1分层区组随机",
        blinding_mode: "double_blind",
        blinded_roles: ["受试者", "研究者", "终点裁定者"],
        blinding_details: "试验药与活性对照吸入装置外观匹配（双模拟）",
        comparator_type: "active",
        comparator_intervention: "已上市LAMA类药物",
        assignment_model: "平行分组，1:1分配，事件驱动",
        center_model: "多中心",
        treatment_switch: { planned: false },
        crossover: { planned: false },
        open_label_extension: { planned: false },
        sample_size_reestimation: { planned: false },
        adaptive_design: { planned: false },
        interim_analysis: { planned: false },
        src_planned: false,
        dmc_planned: true,
        arm_or_cohort_kind: "治疗组",
        arm_or_cohort_labels: ["SYN-COPD-302组", "活性对照组"],
      },
      target_mechanism: "长效muscarinic受体拮抗",
      competitor_target_scope: "同靶点LAMA类药物",
      development_regions: ["中国"],
      design_pattern: "随机、双盲、活性对照、事件驱动、实用性、平行组、多中心确证性研究",
      population_intent: "中重度COPD成人患者",
      key_uncertainties: ["急性加重事件率差异", "长期心血管安全性"],
    },
    picos: {
      design_archetype: "randomized_confirmatory",
      population_summary: "40至85岁中重度COPD试验参与者。",
      inclusion_modules: ["支气管扩张剂后FEV1满足入组阈值", "既往一年内有急性加重史"],
      exclusion_modules: ["哮喘-COPD重叠", "近期呼吸道感染"],
      washout_rules: ["既往LAMA按药代特征完成洗脱"],
      intervention_summary: "SYN-COPD-302每日一次吸入。",
      intervention_dose_regimen: "每日一次，持续52周。",
      intervention_rules: {
        schema_version: "medical_writing_intervention_rules_v1",
        authority: "structured",
        ip_regimens: [
          {
            regimen_id: "syn-copd-302",
            product_name: "SYN-COPD-302",
            product_role: "investigational_product",
            dose_and_frequency: "试验剂量，每日一次吸入",
            route: "经口吸入",
            treatment_period: "双盲治疗期52周",
          },
          {
            regimen_id: "active-comparator-lama",
            product_name: "已上市LAMA活性对照",
            product_role: "active_comparator",
            dose_and_frequency: "标准剂量，每日一次吸入",
            route: "经口吸入",
            treatment_period: "双盲治疗期52周",
          },
        ],
        ip_adjustment_policy: "no_planned_adjustment",
        no_planned_adjustment_statement: "无计划剂量调整；急性加重按方案标准治疗处理。",
        non_ip_treatment_rules: [
          {
            rule_id: "allowed-rescue-saba",
            rule_class: "allowed_cm",
            policy: "allowed",
            agent_or_category: "短效β2受体激动剂救援用药",
            phase_applicability: "全研究期",
          },
          {
            rule_id: "prohibited-other-lama",
            rule_class: "prohibited_cm",
            policy: "prohibited",
            agent_or_category: "其他LAMA和LABA/LAMA复方",
            phase_applicability: "筛选期至治疗期",
          },
        ],
      },
      allowed_concomitant_rules: ["短效β2受体激动剂救援用药", "吸入性糖皮质激素（稳定剂量）"],
      required_background_rules: [],
      prohibited_concomitant_rules: ["其他LAMA", "LABA/LAMA复方"],
      assessment_timing_restrictions: ["肺功能检查前停用短效支气管扩张剂"],
      comparator_summary: "已上市LAMA类药物，每日一次吸入。",
      primary_endpoint: "中重度COPD急性加重年化率（事件驱动）。",
      key_secondary_endpoints: ["第52周谷值FEV1较基线变化"],
      other_secondary_endpoints: ["SGRQ评分较基线变化"],
      exploratory_endpoints: ["急性加重至首次事件时间"],
      safety_endpoints: ["TEAE、SAE、心血管事件"],
      aesi_definitions: ["心血管死亡", "尿潴留"],
      study_epochs: ["筛选期", "导入期", "双盲治疗期", "随访期"],
      visit_strategy: "筛选、导入、基线，治疗期每12周访视，末次给药后随访。",
      estimand_strategy: "主要估计目标评价治疗策略下急性加重年化率；实用性设计允许标准背景治疗。",
      sample_size_strategy: "基于事件驱动设计，达到预设急性加重事件数后分析。",
      statistical_strategy: "主要终点采用负二项回归；非劣效和优效序贯检验。",
    },
    synopsisToken: "SYN-COPD-302治疗慢性阻塞性肺疾病的III期临床研究方案",
    designTokens: ["随机", "双盲", "阳性药对照"],
    aiInstruction: "请仅对本次选中文字做专业医学中文润色，保持事件驱动、随机化、双盲、活性对照、研究阶段、时间点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。",
  },
};

// Disposable rare-disease proof cell used to validate the real visible
// research pipeline without the hundreds of registry records returned by a
// broad RA search. It is intentionally derived from the already validated
// confirmatory shape, then all user-facing identity facts and endpoints are
// replaced with a distinct non-oncology Phase III study.
const pnh_p3 = JSON.parse(JSON.stringify(SCENARIOS.ra_p2));
pnh_p3.id = "pnh_p3";
pnh_p3.round = 1;
pnh_p3.phase = "III期";
pnh_p3.indication = "阵发性睡眠性血红蛋白尿";
pnh_p3.product = "SYN-PNH-301";
pnh_p3.protocolId = "SYN-PNH-301-301";
pnh_p3.projectCode = "QC-FINAL-PNH-P3";
pnh_p3.projectName = "SYN-PNH-301治疗阵发性睡眠性血红蛋白尿的III期临床研究方案 UI证明";
pnh_p3.framing = {
  ...pnh_p3.framing,
  protocol_id: pnh_p3.protocolId,
  version: "V0.1",
  document_title: "SYN-PNH-301治疗阵发性睡眠性血红蛋白尿的III期临床研究方案",
  indication: pnh_p3.indication,
  clinicaltrials_condition_term: "Paroxysmal Nocturnal Hemoglobinuria",
  study_phase: pnh_p3.phase,
  intrinsic_objectives: ["确证性研究"],
  investigational_product: "SYN-PNH-301注射液",
  target_mechanism: "补体通路抑制的长效单克隆抗体",
  competitor_target_scope: "补体抑制剂及同适应症支持治疗",
  design_pattern: "随机、开放标签、活性对照、平行组、多中心确证性研究",
  population_intent: "成人阵发性睡眠性血红蛋白尿患者，既往接受稳定支持治疗",
  product_profile: { ...pnh_p3.framing.product_profile, technology_type: "monoclonal_antibody", exposure_scope: "systemic", administration_routes: ["静脉注射"] },
  key_uncertainties: ["溶血控制的持续性", "长期血栓事件风险"],
};
pnh_p3.picos = {
  ...pnh_p3.picos,
  design_archetype: "randomized_confirmatory",
  population_summary: "18岁及以上、经实验室和临床标准确认的阵发性睡眠性血红蛋白尿患者。",
  inclusion_modules: ["满足阵发性睡眠性血红蛋白尿诊断标准", "筛选期疾病状态和背景治疗稳定"],
  exclusion_modules: ["活动性感染", "近期发生未控制的严重血栓事件"],
  washout_rules: ["既往补体抑制剂按方案规定完成洗脱或转换"],
  intervention_summary: "SYN-PNH-301静脉输注，按体重和方案规定给药。",
  intervention_dose_regimen: "每8周静脉输注一次，持续48周。",
  allowed_concomitant_rules: ["稳定剂量输血支持和铁剂治疗"],
  prohibited_concomitant_rules: ["其他研究性补体抑制剂"],
  assessment_timing_restrictions: ["溶血标志物采样须按中心实验室时间窗完成"],
  comparator_summary: "已批准的补体抑制剂标准治疗，按当地说明书给药。",
  primary_endpoint: "第24周达到无输血且乳酸脱氢酶控制的受试者比例。",
  key_secondary_endpoints: ["第48周无输血比例", "血红蛋白较基线变化"],
  other_secondary_endpoints: ["患者报告疲劳评分变化"],
  exploratory_endpoints: ["血栓事件至首次发生时间"],
  safety_endpoints: ["TEAE、SAE、输注相关反应、感染事件"],
  aesi_definitions: ["脑膜炎球菌感染", "严重溶血"],
  study_epochs: ["筛选期", "随机治疗期", "安全性随访期"],
  visit_strategy: "筛选、基线、每8周给药及评价，末次给药后安全性随访。",
  estimand_strategy: "主要估计目标评价治疗策略下第24周无输血且溶血控制的受试者比例。",
  sample_size_strategy: "基于主要终点组间差异和分层随机假设估算样本量，并预留脱落率。",
  statistical_strategy: "主要终点采用分层CMH方法；连续终点采用协方差分析，安全性采用描述性统计。",
};
pnh_p3.synopsisToken = pnh_p3.framing.document_title;
pnh_p3.designTokens = ["随机", "开放标签", "活性对照"];
pnh_p3.aiInstruction = "请仅对本次选中文字做专业医学中文润色，保持随机化、开放标签、活性对照、研究阶段、给药周期、主要终点及其他受保护研究事实和术语不变；改善句式和可读性，不补造未提供的事实。";
SCENARIOS.pnh_p3 = pnh_p3;

export const ROUND1_IDS = ["asthma_p1", "ra_p2", "hypertension_p3"];
export const ROUND2_IDS = ["migraine_p1", "t2d_p2", "copd_p3"];
