from __future__ import annotations

from pathlib import Path
import sys
import tempfile
import unittest


_ROOT = Path(__file__).resolve().parents[2]
_SCRIPT_DIR = _ROOT / "scripts/qc/protocol_v3"
sys.path.insert(0, str(_SCRIPT_DIR))

from verify_toolchain_rebuild import (  # noqa: E402
    _build_parser,
    LockValidationError,
    ToolchainRebuildError,
    lock_sha256,
    parse_requirement_groups,
    run_import_probe,
    validate_hash_lock,
)


class PythonToolchainLockTests(unittest.TestCase):
    def test_cli_rejects_all_non_manifest_execution_overrides(self) -> None:
        parser = _build_parser()
        for arguments in (
            ["--requirements", "other.in", "--lock", "other.lock"],
            ["--python", "/usr/bin/true"],
            ["--import-module", "unsafe_module"],
        ):
            with self.subTest(arguments=arguments):
                with self.assertRaises(SystemExit) as context:
                    parser.parse_args(arguments)
                self.assertEqual(context.exception.code, 2)

    def test_declared_requirements_are_grouped_and_exclude_pymupdf(self) -> None:
        requirements = _ROOT / "services/api/requirements-protocol-v3.in"

        groups = parse_requirement_groups(requirements)

        self.assertEqual(
            {"runtime_api", "medical_writing", "ocr_pdf", "dev_test"},
            set(groups),
        )
        self.assertIn("fastapi", groups["runtime_api"])
        self.assertIn("python-docx", groups["medical_writing"])
        self.assertIn("pypdfium2", groups["ocr_pdf"])
        self.assertIn("pytest", groups["dev_test"])
        self.assertNotIn("pymupdf", {name.casefold() for values in groups.values() for name in values})

    def test_hash_lock_is_exact_and_hash_complete(self) -> None:
        requirements = _ROOT / "services/api/requirements-protocol-v3.in"
        lock = _ROOT / "services/api/requirements-protocol-v3.lock"

        result = validate_hash_lock(lock, requirements, expected_python="3.12")

        self.assertGreater(result["entry_count"], 0)
        self.assertEqual(result["lock_sha256"], lock_sha256(lock))
        self.assertEqual(result["direct_count"], sum(len(values) for values in parse_requirement_groups(requirements).values()))

    def test_hash_lock_rejects_unhashed_and_duplicate_entries(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            lock = Path(tmp) / "requirements.lock"
            input_file = Path(tmp) / "requirements.in"
            input_file.write_text("# [runtime_api]\nexample==1.0\n", encoding="utf-8")
            lock.write_text(
                "# This file was autogenerated by pip-compile with Python 3.12\n"
                "example==1.0\n"
                "example==1.0 --hash=sha256:" + "0" * 64 + "\n",
                encoding="utf-8",
            )

            with self.assertRaises(LockValidationError):
                validate_hash_lock(lock, input_file, expected_python="3.12")

    def test_hash_lock_rejects_non_sha256_hashes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            lock = Path(tmp) / "requirements.lock"
            input_file = Path(tmp) / "requirements.in"
            input_file.write_text("# [runtime_api]\nexample==1.0\n", encoding="utf-8")
            lock.write_text(
                "# This file was autogenerated by pip-compile with Python 3.12\n"
                "example==1.0 --hash=sha512:" + "0" * 128 + "\n",
                encoding="utf-8",
            )

            with self.assertRaises(LockValidationError):
                validate_hash_lock(lock, input_file, expected_python="3.12")

    def test_import_probe_fails_closed_when_import_writes_to_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "unsafe_module.py").write_text(
                "from pathlib import Path\n"
                "Path('unexpected.sqlite3').write_text('side effect')\n",
                encoding="utf-8",
            )

            with self.assertRaises(ToolchainRebuildError):
                run_import_probe(
                    Path(sys.executable),
                    root,
                    ("unsafe_module",),
                    watch_root=root,
                )


if __name__ == "__main__":
    unittest.main()
