#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = ROOT.parents[1]
sys.path.insert(0, str(ROOT))

from packages.contracts.workbench_contracts import (  # noqa: E402
    ApprovalGate,
    ApprovalState,
    DataBatch,
    EvidenceSource,
    EvidenceSpan,
    Project,
    ProtocolDocument,
    ProtocolSection,
    RiskCase,
    RiskSeverity,
    RiskStatus,
)
from packages.contracts.workbench_contracts.models import (  # noqa: E402
    SubjectMonitoringDrilldown,
    SubjectOverview,
    SubjectTimelineEvent,
    SubjectTimelineEventType,
    SubjectTrendDirection,
    SubjectTrendDomain,
    SubjectTrendMetric,
    SubjectTrendPoint,
    TimepointRiskPrompt,
)


def now(offset_days: int = 0) -> datetime:
    return datetime(2026, 7, 7, 9, 0, tzinfo=timezone.utc) + timedelta(days=offset_days)


def dump_model(item):
    return item.model_dump(mode="json")


def build_subject_monitoring(project_id: str):
    subject_10008 = SubjectOverview(
        project_id=project_id,
        subject_id="10008",
        site_id="10",
        screening_number="10-008",
        randomization_number="R-0108",
        treatment_arm="MG-K10 200 mg Q4W",
        enrollment_status="treatment_period",
        first_dose_date="2026-07-06",
        baseline_visit_date="2026-07-06",
        latest_visit_code="W2",
        latest_visit_label="第2周访视",
        latest_visit_date="2026-07-20",
        key_medical_context=[
            "SAR病程约5年，筛选期rTNSS 9.2分",
            "随机前氯雷他定末次用药距D1不足4天",
            "W1出现轻度头痛AE，ALT一过性轻度升高",
        ],
    )
    timeline_10008 = [
        SubjectTimelineEvent(
            event_id="evt_10008_scr_visit",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-06-24",
            study_day=-12,
            visit_code="SCR",
            visit_label="筛选访视",
            source_domain="SV",
            source_record_id="SV-10008-SCR",
            title="完成筛选访视",
            detail="完成知情同意、病史、合并用药、生命体征、实验室和鼻部症状评分采集。",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_mh_sar",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.MEDICAL_HISTORY,
            event_date="2026-06-24",
            study_day=-12,
            visit_code="SCR",
            visit_label="筛选访视",
            source_domain="MH",
            source_record_id="MH-10008-001",
            title="过敏性鼻炎病史",
            detail="2021年春季起反复鼻塞、流涕、喷嚏，既往花粉季需间断口服抗组胺药。",
            clinical_interpretation="病程和季节性特征支持SAR入组背景。",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_lab_scr_eos",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.LAB,
            event_date="2026-06-24",
            study_day=-12,
            visit_code="SCR",
            visit_label="筛选访视",
            source_domain="LB",
            source_record_id="LB-10008-EOS-SCR",
            title="嗜酸性粒细胞轻度升高",
            detail="EOS 0.62 x10^9/L，实验室参考上限0.52 x10^9/L。",
            result_value="0.62 x10^9/L",
            clinical_interpretation="符合过敏背景，可作为后续安全性趋势基线。",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_cm_loratadine",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.CONCOMITANT_MEDICATION,
            event_date="2026-06-30",
            study_day=-6,
            visit_code="SCR",
            visit_label="筛选期",
            source_domain="CM",
            source_record_id="CM-10008-003",
            title="筛选期使用氯雷他定",
            detail="氯雷他定10 mg qd，2026-06-30至2026-07-05，用于鼻痒和喷嚏。",
            clinical_interpretation="末次用药距离随机不足4天，触发洗脱窗口复核。",
            related_risk_ids=["risk_s6_cm_10008"],
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_d1_visit",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-07-06",
            study_day=1,
            visit_code="D1",
            visit_label="随机/给药访视",
            source_domain="SV",
            source_record_id="SV-10008-D1",
            title="完成随机和首次给药",
            detail="随机至MG-K10 200 mg Q4W组，完成D1给药和基线疗效评分确认。",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_eff_d1",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.EFFICACY_SCORE,
            event_date="2026-07-06",
            study_day=1,
            visit_code="D1",
            visit_label="随机/给药访视",
            source_domain="QS",
            source_record_id="QS-10008-RTNSS-D1",
            title="rTNSS基线评分",
            detail="rTNSS总分9.2分，rTOSS总分5.1分。",
            result_value="rTNSS 9.2; rTOSS 5.1",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_pd_washout",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.PROTOCOL_DEVIATION,
            event_date="2026-07-06",
            study_day=1,
            visit_code="D1",
            visit_label="随机/给药访视",
            source_domain="PD",
            source_record_id="PD-10008-001",
            title="潜在禁止用药洗脱不足",
            detail="D1系统自动标记氯雷他定末次用药与随机间隔不足4天，PD记录待医学确认。",
            clinical_interpretation="需判定是否影响随机资格和主要终点解释。",
            related_risk_ids=["risk_s6_cm_10008"],
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_query_cm",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.QUERY,
            event_date="2026-07-07",
            study_day=2,
            visit_code="D1",
            visit_label="随机/给药访视",
            source_domain="QUERY",
            source_record_id="QRY-10008-CM-001",
            title="CM洗脱窗口Query已发出",
            detail="请中心确认氯雷他定2026-07-05是否为实际末次用药，并补充停药原因。",
            related_risk_ids=["risk_s6_cm_10008"],
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_w1_visit",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-07-13",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="SV",
            source_record_id="SV-10008-W1",
            title="完成W1访视",
            detail="完成疗效评分、AE询问、合并用药复核和安全性实验室采样。",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_ae_headache",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.ADVERSE_EVENT,
            event_date="2026-07-13",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="AE",
            source_record_id="AE-10008-001",
            title="轻度头痛AE",
            detail="轻度头痛，起始于2026-07-12，未用药处理，研究者判断与研究药物可能无关。",
            clinical_interpretation="与ALT轻度升高同访视出现，建议复核伴随用药和恢复情况。",
            related_risk_ids=["risk_s6_lab_10008"],
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_eff_w1",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.EFFICACY_SCORE,
            event_date="2026-07-13",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="QS",
            source_record_id="QS-10008-RTNSS-W1",
            title="W1鼻部症状评分下降",
            detail="rTNSS 6.8分，较基线下降2.4分；rTOSS 3.8分。",
            result_value="rTNSS 6.8; rTOSS 3.8",
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_lab_w1_alt",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.LAB,
            event_date="2026-07-13",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="LB",
            source_record_id="LB-10008-ALT-W1",
            title="ALT轻度高于参考上限",
            detail="ALT 42 U/L，参考范围7-40 U/L，W2复查回落至38 U/L。",
            result_value="42 U/L",
            clinical_interpretation="一过性轻度异常，结合AE和合并用药继续观察。",
            related_risk_ids=["risk_s6_lab_10008"],
        ),
        SubjectTimelineEvent(
            event_id="evt_10008_w2_visit",
            project_id=project_id,
            subject_id="10008",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-07-20",
            study_day=15,
            visit_code="W2",
            visit_label="第2周访视",
            source_domain="SV",
            source_record_id="SV-10008-W2",
            title="完成W2随访",
            detail="鼻部和眼部症状继续改善，ALT复查回落，CM Query仍待中心答复。",
        ),
    ]
    profile_10008 = SubjectMonitoringDrilldown(
        project_id=project_id,
        subject_id="10008",
        generated_at=now(),
        subject=subject_10008,
        timeline=timeline_10008,
        efficacy_trends=[
            SubjectTrendMetric(
                metric_key="rtnss_total",
                metric_label="rTNSS总分",
                domain=SubjectTrendDomain.EFFICACY,
                unit="分",
                direction=SubjectTrendDirection.LOWER_IS_BETTER,
                clinically_meaningful_change=-2.0,
                points=[
                    SubjectTrendPoint(point_id="pt_10008_rtnss_d1", visit_code="D1", visit_label="随机/给药访视", assessment_date="2026-07-06", study_day=1, value=9.2, baseline_value=9.2, change_from_baseline=0.0, source_domain="QS", source_record_id="QS-10008-RTNSS-D1"),
                    SubjectTrendPoint(point_id="pt_10008_rtnss_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-13", study_day=8, value=6.8, baseline_value=9.2, change_from_baseline=-2.4, source_domain="QS", source_record_id="QS-10008-RTNSS-W1"),
                    SubjectTrendPoint(point_id="pt_10008_rtnss_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-20", study_day=15, value=5.1, baseline_value=9.2, change_from_baseline=-4.1, source_domain="QS", source_record_id="QS-10008-RTNSS-W2"),
                ],
            ),
            SubjectTrendMetric(
                metric_key="rtoss_total",
                metric_label="rTOSS总分",
                domain=SubjectTrendDomain.EFFICACY,
                unit="分",
                direction=SubjectTrendDirection.LOWER_IS_BETTER,
                clinically_meaningful_change=-1.0,
                points=[
                    SubjectTrendPoint(point_id="pt_10008_rtoss_d1", visit_code="D1", visit_label="随机/给药访视", assessment_date="2026-07-06", study_day=1, value=5.1, baseline_value=5.1, change_from_baseline=0.0, source_domain="QS", source_record_id="QS-10008-RTOSS-D1"),
                    SubjectTrendPoint(point_id="pt_10008_rtoss_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-13", study_day=8, value=3.8, baseline_value=5.1, change_from_baseline=-1.3, source_domain="QS", source_record_id="QS-10008-RTOSS-W1"),
                    SubjectTrendPoint(point_id="pt_10008_rtoss_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-20", study_day=15, value=2.7, baseline_value=5.1, change_from_baseline=-2.4, source_domain="QS", source_record_id="QS-10008-RTOSS-W2"),
                ],
            ),
        ],
        safety_trends=[
            SubjectTrendMetric(
                metric_key="eosinophil_abs",
                metric_label="嗜酸性粒细胞绝对值",
                domain=SubjectTrendDomain.SAFETY,
                unit="x10^9/L",
                direction=SubjectTrendDirection.STABLE_RANGE,
                points=[
                    SubjectTrendPoint(point_id="pt_10008_eos_scr", visit_code="SCR", visit_label="筛选访视", assessment_date="2026-06-24", study_day=-12, value=0.62, reference_low=0.02, reference_high=0.52, normality="high", risk_flag=True, source_domain="LB", source_record_id="LB-10008-EOS-SCR"),
                    SubjectTrendPoint(point_id="pt_10008_eos_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-13", study_day=8, value=0.58, reference_low=0.02, reference_high=0.52, normality="high", risk_flag=True, source_domain="LB", source_record_id="LB-10008-EOS-W1"),
                    SubjectTrendPoint(point_id="pt_10008_eos_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-20", study_day=15, value=0.46, reference_low=0.02, reference_high=0.52, normality="normal", source_domain="LB", source_record_id="LB-10008-EOS-W2"),
                ],
            ),
            SubjectTrendMetric(
                metric_key="alt",
                metric_label="ALT",
                domain=SubjectTrendDomain.SAFETY,
                unit="U/L",
                direction=SubjectTrendDirection.STABLE_RANGE,
                points=[
                    SubjectTrendPoint(point_id="pt_10008_alt_d1", visit_code="D1", visit_label="随机/给药访视", assessment_date="2026-07-06", study_day=1, value=29, reference_low=7, reference_high=40, normality="normal", source_domain="LB", source_record_id="LB-10008-ALT-D1"),
                    SubjectTrendPoint(point_id="pt_10008_alt_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-13", study_day=8, value=42, reference_low=7, reference_high=40, normality="high", risk_flag=True, source_domain="LB", source_record_id="LB-10008-ALT-W1"),
                    SubjectTrendPoint(point_id="pt_10008_alt_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-20", study_day=15, value=38, reference_low=7, reference_high=40, normality="normal", source_domain="LB", source_record_id="LB-10008-ALT-W2"),
                ],
            ),
        ],
        risk_prompts=[
            TimepointRiskPrompt(
                prompt_id="prompt_10008_d1_washout",
                project_id=project_id,
                subject_id="10008",
                visit_code="D1",
                visit_label="随机/给药访视",
                prompt_date="2026-07-07",
                study_day=2,
                severity=RiskSeverity.HIGH,
                status=RiskStatus.ACTION_REQUIRED,
                risk_type="prohibited_medication_washout",
                title="随机前抗组胺药洗脱窗口不足",
                prompt_text="CM显示氯雷他定末次用药为2026-07-05，距离D1随机不足4天；PD和Query均未关闭，需在判读疗效趋势前完成医学确认。",
                trigger_domains=["CM", "PD", "QUERY"],
                related_event_ids=["evt_10008_cm_loratadine", "evt_10008_pd_washout", "evt_10008_query_cm"],
                related_metric_keys=["rtnss_total", "rtoss_total"],
                related_risk_ids=["risk_s6_cm_10008"],
                evidence_span_ids=["span_protocol_washout", "span_edc_cm_10008", "span_edc_pd_10008"],
                query_id="QRY-10008-CM-001",
                pd_id="PD-10008-001",
                recommended_action="先锁定中心答复和PD判定，再决定是否将该受试者标记为主要疗效解释敏感个例。",
            ),
            TimepointRiskPrompt(
                prompt_id="prompt_10008_w1_lab_ae",
                project_id=project_id,
                subject_id="10008",
                visit_code="W1",
                visit_label="第1周访视",
                prompt_date="2026-07-13",
                study_day=8,
                severity=RiskSeverity.MEDIUM,
                status=RiskStatus.IN_REVIEW,
                risk_type="lab_ae_temporal_cluster",
                title="W1轻度头痛AE与ALT升高同访视出现",
                prompt_text="头痛AE、ALT 42 U/L和EOS轻度升高集中在W1，需要复核是否存在未录入的解热镇痛药或其他合并用药。",
                trigger_domains=["AE", "LB", "CM"],
                related_event_ids=["evt_10008_ae_headache", "evt_10008_lab_w1_alt"],
                related_metric_keys=["alt", "eosinophil_abs"],
                related_risk_ids=["risk_s6_lab_10008"],
                evidence_span_ids=["span_edc_lab_10008"],
                recommended_action="检查W1病历和CM listing；如无新增用药且W2复查正常，可记录为继续观察。",
            ),
        ],
        review_focus=[
            "优先关闭D1洗脱窗口Query和PD判定。",
            "W1安全性异常已回落，但需确认是否有漏录CM。",
            "疗效评分改善明显，解释时需标注随机前用药敏感性。",
        ],
    )

    subject_06021 = SubjectOverview(
        project_id=project_id,
        subject_id="06021",
        site_id="06",
        screening_number="06-021",
        randomization_number="R-0064",
        treatment_arm="安慰剂",
        enrollment_status="treatment_period",
        first_dose_date="2026-07-04",
        baseline_visit_date="2026-07-04",
        latest_visit_code="W4",
        latest_visit_label="第4周访视",
        latest_visit_date="2026-08-01",
        key_medical_context=[
            "既往过敏性结膜炎病史，筛选期眼痒评分偏高",
            "W1记录眼部症状并使用奥洛他定滴眼液",
            "W2电子日记缺失3天并触发PD/Query",
        ],
    )
    timeline_06021 = [
        SubjectTimelineEvent(
            event_id="evt_06021_scr_visit",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-06-20",
            study_day=-14,
            visit_code="SCR",
            visit_label="筛选访视",
            source_domain="SV",
            source_record_id="SV-06021-SCR",
            title="完成筛选访视",
            detail="完成SAR病史、眼部症状、实验室、eDiary培训和入组资格初筛。",
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_mh_ocular",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.MEDICAL_HISTORY,
            event_date="2026-06-20",
            study_day=-14,
            visit_code="SCR",
            visit_label="筛选访视",
            source_domain="MH",
            source_record_id="MH-06021-002",
            title="既往过敏性结膜炎",
            detail="2023年起花粉季反复眼痒、流泪，既往间断使用抗过敏滴眼液。",
            clinical_interpretation="后续眼部AE需区分既往病情波动、伴随用药和研究治疗后新发/加重。",
            related_risk_ids=["risk_s6_ae_06021"],
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_lab_scr_eos",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.LAB,
            event_date="2026-06-20",
            study_day=-14,
            visit_code="SCR",
            visit_label="筛选访视",
            source_domain="LB",
            source_record_id="LB-06021-EOS-SCR",
            title="EOS接近参考上限",
            detail="EOS 0.49 x10^9/L，参考范围0.02-0.52 x10^9/L。",
            result_value="0.49 x10^9/L",
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_d1_visit",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-07-04",
            study_day=1,
            visit_code="D1",
            visit_label="随机/给药访视",
            source_domain="SV",
            source_record_id="SV-06021-D1",
            title="完成随机和首次给药",
            detail="随机至安慰剂组，完成基线症状评分和给药。",
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_eff_d1",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.EFFICACY_SCORE,
            event_date="2026-07-04",
            study_day=1,
            visit_code="D1",
            visit_label="随机/给药访视",
            source_domain="QS",
            source_record_id="QS-06021-RTNSS-D1",
            title="rTNSS基线评分",
            detail="rTNSS总分8.7分，rTOSS总分4.8分。",
            result_value="rTNSS 8.7; rTOSS 4.8",
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_w1_visit",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-07-11",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="SV",
            source_record_id="SV-06021-W1",
            title="完成W1访视",
            detail="眼部症状较基线加重，中心补录AE并新增奥洛他定滴眼液。",
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_ae_conjunctivitis",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.ADVERSE_EVENT,
            event_date="2026-07-11",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="AE",
            source_record_id="AE-06021-004",
            title="轻度结膜炎AE补录",
            detail="W1补录轻度结膜炎，起始日期2026-07-09，未导致停药。",
            clinical_interpretation="与既往过敏性结膜炎和同访视CM存在时间顺序复核需求。",
            related_risk_ids=["risk_s6_ae_06021"],
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_cm_eye_drop",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.CONCOMITANT_MEDICATION,
            event_date="2026-07-11",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="CM",
            source_record_id="CM-06021-002",
            title="新增奥洛他定滴眼液",
            detail="奥洛他定滴眼液bid，2026-07-10开始，用于眼痒和流泪。",
            clinical_interpretation="需确认是否属于允许的眼部救援用药及是否影响眼部症状评分解释。",
            related_risk_ids=["risk_s6_ae_06021"],
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_eff_w1",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.EFFICACY_SCORE,
            event_date="2026-07-11",
            study_day=8,
            visit_code="W1",
            visit_label="第1周访视",
            source_domain="QS",
            source_record_id="QS-06021-RTNSS-W1",
            title="W1症状评分改善有限",
            detail="rTNSS 7.9分，较基线下降0.8分；rTOSS 5.2分，较基线升高0.4分。",
            result_value="rTNSS 7.9; rTOSS 5.2",
            clinical_interpretation="眼部症状上升与AE/CM记录同向，需要结合安全性和疗效趋势审阅。",
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_pd_diary",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.PROTOCOL_DEVIATION,
            event_date="2026-07-18",
            study_day=15,
            visit_code="W2",
            visit_label="第2周访视",
            source_domain="PD",
            source_record_id="PD-06021-002",
            title="W2电子日记缺失",
            detail="W2前7天窗口内缺失3天鼻部症状日记，超过方案允许阈值，PD待关闭。",
            clinical_interpretation="直接影响W2疗效评分可解释性。",
            related_risk_ids=["risk_s6_query_06021"],
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_query_diary",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.QUERY,
            event_date="2026-07-19",
            study_day=16,
            visit_code="W2",
            visit_label="第2周访视",
            source_domain="QUERY",
            source_record_id="QRY-06021-QS-002",
            title="W2 eDiary缺失Query",
            detail="请中心说明2026-07-15至2026-07-17日记缺失原因，并确认是否有纸质记录可追溯。",
            related_risk_ids=["risk_s6_query_06021"],
        ),
        SubjectTimelineEvent(
            event_id="evt_06021_w4_visit",
            project_id=project_id,
            subject_id="06021",
            event_type=SubjectTimelineEventType.VISIT,
            event_date="2026-08-01",
            study_day=29,
            visit_code="W4",
            visit_label="第4周访视",
            source_domain="SV",
            source_record_id="SV-06021-W4",
            title="完成W4访视",
            detail="眼部症状缓解，eDiary依从性恢复，仍需关闭W2 Query和PD。",
        ),
    ]
    profile_06021 = SubjectMonitoringDrilldown(
        project_id=project_id,
        subject_id="06021",
        generated_at=now(),
        subject=subject_06021,
        timeline=timeline_06021,
        efficacy_trends=[
            SubjectTrendMetric(
                metric_key="rtnss_total",
                metric_label="rTNSS总分",
                domain=SubjectTrendDomain.EFFICACY,
                unit="分",
                direction=SubjectTrendDirection.LOWER_IS_BETTER,
                clinically_meaningful_change=-2.0,
                points=[
                    SubjectTrendPoint(point_id="pt_06021_rtnss_d1", visit_code="D1", visit_label="随机/给药访视", assessment_date="2026-07-04", study_day=1, value=8.7, baseline_value=8.7, change_from_baseline=0.0, source_domain="QS", source_record_id="QS-06021-RTNSS-D1"),
                    SubjectTrendPoint(point_id="pt_06021_rtnss_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-11", study_day=8, value=7.9, baseline_value=8.7, change_from_baseline=-0.8, source_domain="QS", source_record_id="QS-06021-RTNSS-W1", note="改善未达到预设临床关注阈值。"),
                    SubjectTrendPoint(point_id="pt_06021_rtnss_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-18", study_day=15, value=8.1, baseline_value=8.7, change_from_baseline=-0.6, risk_flag=True, source_domain="QS", source_record_id="QS-06021-RTNSS-W2", note="W2 eDiary缺失3天，评分可解释性受限。"),
                    SubjectTrendPoint(point_id="pt_06021_rtnss_w4", visit_code="W4", visit_label="第4周访视", assessment_date="2026-08-01", study_day=29, value=5.4, baseline_value=8.7, change_from_baseline=-3.3, source_domain="QS", source_record_id="QS-06021-RTNSS-W4"),
                ],
            ),
            SubjectTrendMetric(
                metric_key="rtoss_total",
                metric_label="rTOSS总分",
                domain=SubjectTrendDomain.EFFICACY,
                unit="分",
                direction=SubjectTrendDirection.LOWER_IS_BETTER,
                clinically_meaningful_change=-1.0,
                points=[
                    SubjectTrendPoint(point_id="pt_06021_rtoss_d1", visit_code="D1", visit_label="随机/给药访视", assessment_date="2026-07-04", study_day=1, value=4.8, baseline_value=4.8, change_from_baseline=0.0, source_domain="QS", source_record_id="QS-06021-RTOSS-D1"),
                    SubjectTrendPoint(point_id="pt_06021_rtoss_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-11", study_day=8, value=5.2, baseline_value=4.8, change_from_baseline=0.4, risk_flag=True, source_domain="QS", source_record_id="QS-06021-RTOSS-W1"),
                    SubjectTrendPoint(point_id="pt_06021_rtoss_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-18", study_day=15, value=5.0, baseline_value=4.8, change_from_baseline=0.2, risk_flag=True, source_domain="QS", source_record_id="QS-06021-RTOSS-W2"),
                    SubjectTrendPoint(point_id="pt_06021_rtoss_w4", visit_code="W4", visit_label="第4周访视", assessment_date="2026-08-01", study_day=29, value=3.1, baseline_value=4.8, change_from_baseline=-1.7, source_domain="QS", source_record_id="QS-06021-RTOSS-W4"),
                ],
            ),
        ],
        safety_trends=[
            SubjectTrendMetric(
                metric_key="eosinophil_abs",
                metric_label="嗜酸性粒细胞绝对值",
                domain=SubjectTrendDomain.SAFETY,
                unit="x10^9/L",
                direction=SubjectTrendDirection.STABLE_RANGE,
                points=[
                    SubjectTrendPoint(point_id="pt_06021_eos_scr", visit_code="SCR", visit_label="筛选访视", assessment_date="2026-06-20", study_day=-14, value=0.49, reference_low=0.02, reference_high=0.52, normality="normal", source_domain="LB", source_record_id="LB-06021-EOS-SCR"),
                    SubjectTrendPoint(point_id="pt_06021_eos_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-11", study_day=8, value=0.57, reference_low=0.02, reference_high=0.52, normality="high", risk_flag=True, source_domain="LB", source_record_id="LB-06021-EOS-W1"),
                    SubjectTrendPoint(point_id="pt_06021_eos_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-18", study_day=15, value=0.55, reference_low=0.02, reference_high=0.52, normality="high", risk_flag=True, source_domain="LB", source_record_id="LB-06021-EOS-W2"),
                    SubjectTrendPoint(point_id="pt_06021_eos_w4", visit_code="W4", visit_label="第4周访视", assessment_date="2026-08-01", study_day=29, value=0.42, reference_low=0.02, reference_high=0.52, normality="normal", source_domain="LB", source_record_id="LB-06021-EOS-W4"),
                ],
            ),
            SubjectTrendMetric(
                metric_key="ocular_symptom_score",
                metric_label="眼部症状安全性关注评分",
                domain=SubjectTrendDomain.SAFETY,
                unit="分",
                direction=SubjectTrendDirection.LOWER_IS_BETTER,
                points=[
                    SubjectTrendPoint(point_id="pt_06021_ocular_d1", visit_code="D1", visit_label="随机/给药访视", assessment_date="2026-07-04", study_day=1, value=2.0, baseline_value=2.0, change_from_baseline=0.0, source_domain="QS", source_record_id="QS-06021-OCULAR-D1"),
                    SubjectTrendPoint(point_id="pt_06021_ocular_w1", visit_code="W1", visit_label="第1周访视", assessment_date="2026-07-11", study_day=8, value=4.0, baseline_value=2.0, change_from_baseline=2.0, risk_flag=True, source_domain="QS", source_record_id="QS-06021-OCULAR-W1"),
                    SubjectTrendPoint(point_id="pt_06021_ocular_w2", visit_code="W2", visit_label="第2周访视", assessment_date="2026-07-18", study_day=15, value=3.0, baseline_value=2.0, change_from_baseline=1.0, risk_flag=True, source_domain="QS", source_record_id="QS-06021-OCULAR-W2"),
                    SubjectTrendPoint(point_id="pt_06021_ocular_w4", visit_code="W4", visit_label="第4周访视", assessment_date="2026-08-01", study_day=29, value=1.0, baseline_value=2.0, change_from_baseline=-1.0, source_domain="QS", source_record_id="QS-06021-OCULAR-W4"),
                ],
            ),
        ],
        risk_prompts=[
            TimepointRiskPrompt(
                prompt_id="prompt_06021_w1_ocular",
                project_id=project_id,
                subject_id="06021",
                visit_code="W1",
                visit_label="第1周访视",
                prompt_date="2026-07-11",
                study_day=8,
                severity=RiskSeverity.MEDIUM,
                status=RiskStatus.IN_REVIEW,
                risk_type="ae_mh_cm_temporal_mismatch",
                title="眼部AE、既往史和滴眼液时间顺序需复核",
                prompt_text="W1补录结膜炎AE、MH提示既往过敏性结膜炎，同日新增奥洛他定；需确认AE为新发还是既往病情加重，并核对是否影响rTOSS解释。",
                trigger_domains=["AE", "MH", "CM", "QS"],
                related_event_ids=["evt_06021_mh_ocular", "evt_06021_ae_conjunctivitis", "evt_06021_cm_eye_drop", "evt_06021_eff_w1"],
                related_metric_keys=["rtoss_total", "ocular_symptom_score", "eosinophil_abs"],
                related_risk_ids=["risk_s6_ae_06021"],
                evidence_span_ids=["span_ib_conjunctivitis"],
                recommended_action="要求中心补充AE判定依据和CM是否为救援用药；医学经理确认后再关闭风险。",
            ),
            TimepointRiskPrompt(
                prompt_id="prompt_06021_w2_diary_query",
                project_id=project_id,
                subject_id="06021",
                visit_code="W2",
                visit_label="第2周访视",
                prompt_date="2026-07-19",
                study_day=16,
                severity=RiskSeverity.HIGH,
                status=RiskStatus.ACTION_REQUIRED,
                risk_type="missing_efficacy_diary",
                title="W2疗效评分缺失窗口已触发PD和Query",
                prompt_text="W2前7天eDiary缺失3天，rTNSS/rTOSS点位被标记为风险点；该时间点不宜直接用于个例疗效判断，需等待Query和PD关闭。",
                trigger_domains=["QS", "PD", "QUERY"],
                related_event_ids=["evt_06021_pd_diary", "evt_06021_query_diary"],
                related_metric_keys=["rtnss_total", "rtoss_total"],
                related_risk_ids=["risk_s6_query_06021"],
                evidence_span_ids=["span_edc_query_06021"],
                query_id="QRY-06021-QS-002",
                pd_id="PD-06021-002",
                recommended_action="确认缺失原因、是否存在纸质补录来源，以及SAP中对缺失日记的处理规则。",
            ),
        ],
        review_focus=[
            "先区分W1眼部AE是既往史波动还是新发/加重事件。",
            "W2疗效评分需等待PD/Query关闭后再进入个例疗效判断。",
            "W4症状改善可作为恢复趋势，但不能抵消W2缺失数据风险。",
        ],
    )

    return [profile_10008, profile_06021]


def build_demo():
    project = Project(
        project_id="proj_mgk10_sar_demo",
        project_code="MG-K10-SAR-DEMO",
        project_name="MG-K10 SAR 医学经理工作台演示项目",
        indication="季节性过敏性鼻炎",
        product_name="MG-K10",
        study_phase="III",
        protocol_id="MG-K10-SAR-001",
        protocol_version="V2.1",
        protocol_date="2025-09-19",
        created_at=now(-30),
        updated_at=now(),
    )

    evidence_sources = [
        EvidenceSource(
            evidence_id="ev_protocol_v21",
            project_id=project.project_id,
            source_type="protocol",
            title="MG-K10-SAR-001 研究方案 V2.1",
            file_path="references/protocol/MG-K10-SAR-001_protocol_v2_1.docx",
            version_label="V2.1",
            created_at=now(-20),
        ),
        EvidenceSource(
            evidence_id="ev_edc_batch_003",
            project_id=project.project_id,
            source_type="edc_listing",
            title="原始数据 listing Batch 003",
            file_path="demo_data/listings/edc_listing_batch_003.xlsx",
            version_label="batch_003",
            data_batch_id="batch_003",
            created_at=now(-1),
        ),
        EvidenceSource(
            evidence_id="ev_ib",
            project_id=project.project_id,
            source_type="ib",
            title="MG-K10 研究者手册",
            file_path="references/ib/mgk10_ib_clean.docx",
            version_label="2025-06-26",
            created_at=now(-18),
        ),
    ]

    evidence_spans = [
        EvidenceSpan(
            span_id="span_protocol_washout",
            evidence_id="ev_protocol_v21",
            page=62,
            quote="抗组胺药随机前需停用4天，白三烯调节剂需停用1周。",
            normalized_value="antihistamine washout 4 days; leukotriene modifier washout 7 days",
        ),
        EvidenceSpan(
            span_id="span_edc_cm_10008",
            evidence_id="ev_edc_batch_003",
            sheet="CM",
            row=128,
            column="用药名称/开始日期/结束日期",
            quote="10008 氯雷他定，2026-06-30 至 2026-07-05",
            normalized_value="loratadine 2026-06-30 to 2026-07-05",
        ),
        EvidenceSpan(
            span_id="span_ib_conjunctivitis",
            evidence_id="ev_ib",
            page=44,
            quote="同靶点药物已知眼部事件包括结膜炎、角膜炎等。",
            normalized_value="IL-4R related ocular risks",
        ),
        EvidenceSpan(
            span_id="span_edc_pd_10008",
            evidence_id="ev_edc_batch_003",
            sheet="PD",
            row=42,
            column="偏离类别/发生日期/状态",
            quote="10008 禁止用药洗脱窗口不足，2026-07-06，待医学确认",
            normalized_value="potential washout PD on 2026-07-06; pending medical confirmation",
        ),
        EvidenceSpan(
            span_id="span_edc_lab_10008",
            evidence_id="ev_edc_batch_003",
            sheet="LB",
            row=223,
            column="ALT/EOS/访视",
            quote="10008 W1 ALT 42 U/L，EOS 0.58 x10^9/L；W2 ALT 38 U/L",
            normalized_value="W1 ALT mildly high and W2 normalized",
        ),
        EvidenceSpan(
            span_id="span_edc_query_06021",
            evidence_id="ev_edc_batch_003",
            sheet="QUERY",
            row=87,
            column="Query文本/状态",
            quote="06021 W2 eDiary缺失3天，请确认原因及是否有纸质记录",
            normalized_value="W2 eDiary missing three days; query open",
        ),
    ]

    batches = [
        DataBatch(
            batch_id=f"batch_{idx:03d}",
            project_id=project.project_id,
            batch_label=f"原始数据 listing Batch {idx:03d}",
            extract_date=f"2026-0{idx + 4}-28",
            uploaded_by="medical_manager",
            status="run" if idx < 3 else "mapped",
            source_file_ids=[f"ev_edc_batch_{idx:03d}"],
            previous_batch_id=f"batch_{idx - 1:03d}" if idx > 1 else None,
            row_count=8800 + idx * 560,
            subject_count=160 + idx * 5,
            site_count=22 + idx,
            created_at=now(-10 + idx),
        )
        for idx in range(1, 4)
    ]

    risks = [
        RiskCase(
            risk_id="risk_s6_cm_10008",
            project_id=project.project_id,
            module="medical_monitoring",
            risk_type="prohibited_medication",
            title="10008 随机前抗组胺药洗脱不足",
            subject_id="10008",
            site_id="10",
            severity=RiskSeverity.HIGH,
            status=RiskStatus.ACTION_REQUIRED,
            source_batch_id="batch_003",
            rule_id="S6-CM-WASHOUT-ANTIHISTAMINE",
            evidence_span_ids=["span_protocol_washout", "span_edc_cm_10008"],
            rationale="原始数据 listing 显示受试者在随机前4天窗口内使用氯雷他定，需确认是否构成洗脱不足或已登记 PD。",
            recommended_action="医学经理复核 CM 与 PD listing；如未登记，转为潜在方案偏离风险。",
            created_at=now(-1),
        ),
        RiskCase(
            risk_id="risk_s6_ae_06021",
            project_id=project.project_id,
            module="medical_monitoring",
            risk_type="ae_mh_missing",
            title="06021 眼部异常与AE记录不一致",
            subject_id="06021",
            site_id="06",
            severity=RiskSeverity.MEDIUM,
            status=RiskStatus.IN_REVIEW,
            source_batch_id="batch_003",
            rule_id="S6-AE-OCULAR-IB",
            evidence_span_ids=["span_ib_conjunctivitis"],
            rationale="眼部相关症状与同靶点已知风险相关，但 AE listing 未见对应事件，需医学复核。",
            recommended_action="核对病历、AE、合并用药和眼科检查；必要时发起 query。",
            created_at=now(-2),
        ),
        RiskCase(
            risk_id="risk_s6_lab_10008",
            project_id=project.project_id,
            module="medical_monitoring",
            risk_type="lab_ae_temporal_cluster",
            title="10008 W1 ALT轻度升高与头痛AE同访视出现",
            subject_id="10008",
            site_id="10",
            severity=RiskSeverity.MEDIUM,
            status=RiskStatus.IN_REVIEW,
            source_batch_id="batch_003",
            rule_id="S6-LB-AE-SAME-VISIT",
            evidence_span_ids=["span_edc_lab_10008"],
            rationale="W1 ALT 42 U/L略高于参考上限，同时补录轻度头痛AE；需确认是否存在未录入的伴随用药或其他诱因。",
            recommended_action="复核W1病历、CM listing和W2复查结果；若W2已恢复且无新增CM，可记录为继续观察。",
            created_at=now(-1),
        ),
        RiskCase(
            risk_id="risk_s6_query_06021",
            project_id=project.project_id,
            module="medical_monitoring",
            risk_type="missing_efficacy_score_query",
            title="06021 W2疗效日记缺失并触发Query",
            subject_id="06021",
            site_id="06",
            severity=RiskSeverity.HIGH,
            status=RiskStatus.ACTION_REQUIRED,
            source_batch_id="batch_003",
            rule_id="S6-QS-MISSING-W2-DIARY",
            evidence_span_ids=["span_edc_query_06021"],
            rationale="W2关键评估窗口内电子日记缺失3天，rTNSS/rTOSS点位可解释性受限，且Query仍未关闭。",
            recommended_action="要求中心说明缺失原因并确认是否存在可追溯纸质记录；医学经理需在趋势解读中标记该时间点。",
            created_at=now(-1),
        ),
        RiskCase(
            risk_id="risk_s3_hist_31014",
            project_id=project.project_id,
            module="eligibility_review",
            risk_type="eligibility",
            title="31014 既往诊断年限仅有筛选病史陈述",
            subject_id="31014",
            site_id="31",
            severity=RiskSeverity.LOW,
            status=RiskStatus.TRIAGED,
            rule_id="IN-HISTORY-DURATION",
            evidence_span_ids=[],
            rationale="历史诊断/病程要求需要历史资料溯源，筛选病史记录不足以 plain pass。",
            recommended_action="补充既往诊断证明、门诊病历或历史处方作为来源。",
            created_at=now(-3),
        ),
        RiskCase(
            risk_id="risk_s8_endpoint_gap",
            project_id=project.project_id,
            module="medical_writing",
            risk_type="writing_gap",
            title="主要终点与统计假设缺少证据挂载",
            severity=RiskSeverity.HIGH,
            status=RiskStatus.NEW,
            rule_id="S8-PROTOCOL-ENDPOINT-EVIDENCE",
            evidence_span_ids=[],
            rationale="Protocol 主要终点章节已有草稿，但尚未挂载竞品方案、指导原则或统计依据。",
            recommended_action="从证据调研与方案设计资料库补充终点选择依据，并由医学经理确认。",
            created_at=now(-1),
        ),
    ]

    document_id = "protocol_demo_v0_1"
    sections = [
        ProtocolSection(
            section_id="sec_synopsis",
            document_id=document_id,
            heading="方案概要",
            ich_m11_anchor="Synopsis",
            completion_status="drafted",
            evidence_coverage=0.65,
            risk_count=1,
            content_blocks=[{"type": "paragraph", "text": "本研究为评价 MG-K10 治疗季节性过敏性鼻炎有效性和安全性的多中心、随机、双盲、安慰剂对照 III 期研究。"}],
        ),
        ProtocolSection(
            section_id="sec_objectives_endpoints",
            document_id=document_id,
            heading="研究目的与终点",
            ich_m11_anchor="Objectives and Endpoints",
            completion_status="in_review",
            evidence_coverage=0.35,
            risk_count=1,
            content_blocks=[{"type": "paragraph", "text": "主要目的为评价 MG-K10 相较安慰剂改善鼻部症状的疗效。主要终点拟为治疗期关键时间窗内 rTNSS 较基线变化。"}],
        ),
        ProtocolSection(
            section_id="sec_eligibility",
            document_id=document_id,
            heading="入选与排除标准",
            ich_m11_anchor="Eligibility Criteria",
            completion_status="drafted",
            evidence_coverage=0.72,
            risk_count=0,
            content_blocks=[{"type": "criteria_table", "rows": 18}],
        ),
        ProtocolSection(
            section_id="sec_soa",
            document_id=document_id,
            heading="研究流程与评估时间表",
            ich_m11_anchor="Schedule of Activities",
            completion_status="drafted",
            evidence_coverage=0.58,
            risk_count=0,
            content_blocks=[{"type": "soa_table", "visits": ["筛选", "D1", "W1", "W2", "W4", "W8", "EOT"]}],
        ),
    ]
    protocol = ProtocolDocument(
        document_id=document_id,
        project_id=project.project_id,
        protocol_id=project.protocol_id,
        version="draft_v0_1",
        sections=sections,
        quality_gates=[
            {"gate_id": "qg_evidence", "label": "关键终点证据覆盖", "status": "blocking"},
            {"gate_id": "qg_soa_consistency", "label": "SoA 与评估章节一致性", "status": "warning"},
        ],
    )

    approvals = [
        ApprovalGate(
            approval_id="approval_protocol_sec_objectives",
            project_id=project.project_id,
            target_type="medical_writing_protocol_section",
            target_id="sec_objectives_endpoints",
            state=ApprovalState.IN_MEDICAL_REVIEW,
            requested_by="medical_writer_ai",
            reviewed_by="medical_manager",
            review_comments="需补充终点选择依据后再批准。",
            created_at=now(-1),
            updated_at=now(-1),
        ),
        ApprovalGate(
            approval_id="approval_medical_monitoring_batch003",
            project_id=project.project_id,
            target_type="medical_monitoring_risk_batch",
            target_id="batch_003",
            state=ApprovalState.AI_DRAFT,
            requested_by="system",
            review_comments="原始数据 listing Batch 003 风险结果待医学经理复核。",
            created_at=now(-1),
            updated_at=now(-1),
        ),
    ]
    subject_monitoring_profiles = build_subject_monitoring(project.project_id)

    return {
        "projects": [dump_model(project)],
        "evidence_sources": [dump_model(item) for item in evidence_sources],
        "evidence_spans": [dump_model(item) for item in evidence_spans],
        "data_batches": [dump_model(item) for item in batches],
        "risk_cases": [dump_model(item) for item in risks],
        "subject_monitoring_profiles": [dump_model(item) for item in subject_monitoring_profiles],
        "protocol_documents": [dump_model(protocol)],
        "ai_runs": [],
        "revision_threads": [],
        "approval_gates": [dump_model(item) for item in approvals],
    }


def main():
    output = PROJECT_ROOT / "demo_data" / "workbench_demo_v0_1.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(build_demo(), ensure_ascii=False, indent=2), encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
